local _, ns = ...

ns.defaults = {
    global = {
        lastSeenChangelogVersion = "",
        language = "auto",
    },
    profile = {
        schemaVersion = 2,
        enabled = true,
        locked = false,
        scale = 1,
        spacing = 7,
        showPanelBackground = false,
        showHeader = false,
        showAbilityName = false,
        showPriorityBadge = false,
        showIconBorder = true,
        showHotkey = true,
        showCooldown = true,
        showRoleLabel = true,
        hudFont = "friz",
        hudFontOutline = "OUTLINE",
        primaryIconSize = 62,
        secondaryIconSize = 46,
        roleLabelSize = 10,
        roleLabelOffsetY = 0,
        hotkeyFontSize = 9,
        cooldownFontSize = 14,
        abilityNameFontSize = 9,
        accentColor = { 0.02, 0.88, 0.7 },
        hotkeyColor = { 0.92, 0.98, 0.97 },
        cooldownColor = { 1.0, 0.86, 0.32 },
        roleColors = {
            AOE = { 0.2, 0.82, 1.0 },
            SINGLE = { 0.35, 1.0, 0.62 },
            BURST = { 1.0, 0.55, 0.18 },
            SAVE = { 0.15, 0.95, 0.72 },
        },
        rotationPreset = "shaman_totemic_mythicplus",
        healingMode = "standard",
        rotationDataVersion = 12108,
        bindings = {},
        point = "CENTER",
        relativePoint = "CENTER",
        x = 0,
        y = -165,
        slots = ns.AbilityLibrary:BuildPresetSlots("shaman_totemic_mythicplus", {}),
    },
}
