local _, ns = ...

local clientLocale = type(GetLocale) == "function" and GetLocale() or "enUS"

local enUS = {
    ["Einzelziel"] = "Single Target",
    ["Mana sparen"] = "Mana Saving",
    ["Hotkey %s ist mehrfach belegt: %s"] = "Hotkey %s is assigned more than once: %s",
    ["Lokalen Zustand außerhalb des Kampfes abgeglichen."] = "Local state reconciled outside combat.",
    ["Heilmodus: %s"] = "Healing mode: %s",
    ["Prioritätsplatz %s ist nicht belegt."] = "Priority slot %s is not configured.",
    ["Downpour lokal wiederhergestellt."] = "Downpour restored locally.",
    ["%s lokal zurückerstattet."] = "%s refunded locally.",
    ["Lokale Cooldown-Simulation zurückgesetzt."] = "Local cooldown simulation reset.",
    ["Unbekannte Fähigkeit. Beispiele: /hh refund hst, riptide, downpour, rain"] = "Unknown ability. Examples: /hh refund hst, riptide, downpour, rain",
    ["Modi: standard, aoe, single, mana, next"] = "Modes: standard, aoe, single, mana, next",
    ["Anzeige gesperrt."] = "Display locked.",
    ["Anzeige entsperrt."] = "Display unlocked.",
    ["Talent-Snapshot noch nicht verfügbar; bestehende Preset-Annahmen bleiben aktiv."] = "Talent snapshot is not available yet; existing preset assumptions remain active.",
    ["JA"] = "YES",
    ["nein"] = "no",
    ["Talente (Config %s): %s"] = "Talents (Config %s): %s",
    ["Nicht belegt"] = "Not configured",
    ["Übersicht"] = "Overview",
    ["Anzeige, Verhalten und Größe des statischen Priority-Trackers."] = "Display, behavior and size of the static priority tracker.",
    ["Tracker anzeigen"] = "Show tracker",
    ["Blendet die HeliHeal-Prioritätsleiste ein oder aus."] = "Show or hide the HeliHeal priority strip.",
    ["Position sperren"] = "Lock position",
    ["Verhindert das versehentliche Verschieben der Anzeige."] = "Prevents accidentally moving the display.",
    ["UI-Skalierung"] = "UI scale",
    ["Skaliert die vollständige Priority-Anzeige."] = "Scales the complete priority display.",
    ["Icon-Abstand"] = "Icon spacing",
    ["Bestimmt den Abstand zwischen Empfehlung und Folgeslots."] = "Controls the gap between the recommendation icons.",
    ["Sprache"] = "Language",
    ["Standard: WoW-Clientsprache. Ein Wechsel lädt die UI neu."] = "Default: WoW client language. Changing it reloads the UI.",
    ["CLIENTSPRACHE"] = "CLIENT LANGUAGE",
    ["DEUTSCH"] = "GERMAN",
    ["LOKALE TIMER ZURÜCKSETZEN"] = "RESET LOCAL TIMERS",
    ["ANZEIGE ZENTRIEREN"] = "CENTER DISPLAY",
    ["Inputs können während des Kampfes nicht neu belegt werden."] = "Inputs cannot be rebound during combat.",
    ["TASTE DRÜCKEN …"] = "PRESS A KEY …",
    ["Standard bleibt das Guide-Paket; Kontextmodi verändern nur dessen lokale Reihenfolge."] = "Standard retains the guide pack; context modes only change its local order.",
    ["EINZELZIEL"] = "SINGLE TARGET",
    ["MANA SPAREN"] = "MANA SAVING",
    ["FESTE GUIDE-FÄHIGKEIT"] = "STATIC GUIDE ABILITY",
    ["BEOBACHTETER ACTIONBAR-HOTKEY"] = "OBSERVED ACTION BAR HOTKEY",
    ["HUD-Elemente"] = "HUD Elements",
    ["Reduziere die Anzeige auf das Wesentliche oder aktiviere einzelne Details."] = "Reduce the display to essentials or enable individual details.",
    ["Panel-Hintergrund"] = "Panel background",
    ["Dunkler gemeinsamer Hintergrund um alle Icons."] = "Shared dark background around all icons.",
    ["HeliHeal-Header"] = "HeliHeal header",
    ["Zeigt die Überschrift über der Priority-Leiste."] = "Shows the heading above the priority strip.",
    ["Fähigkeitsname"] = "Ability name",
    ["Blendet den Namen der Fähigkeit am Icon ein."] = "Shows the ability name above its icon.",
    ["Prioritätsbadge"] = "Priority badge",
    ["Zeigt P1 bis P5 direkt auf dem jeweiligen Icon."] = "Shows P1 through P5 on the corresponding icon.",
    ["Icon-Rahmen"] = "Icon border",
    ["Schmaler Rahmen und Schatten um jedes Spell-Icon."] = "Thin border and shadow around every spell icon.",
    ["Hotkey"] = "Hotkey",
    ["Zeigt den beobachteten Input unter dem Icon."] = "Shows the observed input below the icon.",
    ["Cooldown-Zahl"] = "Cooldown number",
    ["Zeigt den lokal simulierten Cooldown mittig auf dem Icon."] = "Shows the locally simulated cooldown on the icon.",
    ["SCHRIFT, GRÖSSE & FARBEN"] = "FONT, SIZE & COLORS",
    ["HUD-Schriftart"] = "HUD font",
    ["Linksklick nächste, Rechtsklick vorherige Schriftart."] = "Left-click for the next font, right-click for the previous font.",
    ["Ohne Kontur"] = "No outline",
    ["Normale Kontur"] = "Normal outline",
    ["Starke Kontur"] = "Thick outline",
    ["Textkontur"] = "Text outline",
    ["Legt die Lesbarkeit aller Texte auf den Spell-Icons fest."] = "Controls the outline and readability of all text on spell icons.",
    ["Haupt-Icon-Größe"] = "Primary icon size",
    ["Größe der aktuell empfohlenen Fähigkeit."] = "Size of the currently recommended ability.",
    ["Folge-Icon-Größe"] = "Secondary icon size",
    ["Größe der vier nachfolgenden Empfehlungen."] = "Size of the four following recommendations.",
    ["Rollen-Textgröße"] = "Role text size",
    ["Größe von AOE, SINGLE, BURST und SAVE."] = "Size of AOE, SINGLE, BURST and SAVE labels.",
    ["Rollen-Position"] = "Role position",
    ["Verschiebt den Rollen-Hinweis vertikal im Icon."] = "Moves the role label vertically inside the icon.",
    ["Hotkey-Textgröße"] = "Hotkey text size",
    ["Größe der Tastenbezeichnung unter dem Icon."] = "Size of the key label below the icon.",
    ["Cooldown-Textgröße"] = "Cooldown text size",
    ["Größe des lokalen Timers und der Aufladungsanzeige."] = "Size of local timers and charge counters.",
    ["Namens-Textgröße"] = "Ability name size",
    ["Größe von Fähigkeitsname und optionalem Header."] = "Size of the ability name and optional header.",
    ["AKZENT"] = "ACCENT",
    ["HUD-Akzentfarbe"] = "HUD accent color",
    ["Farbe für aktive Rahmen, Header und Prioritätsbadge."] = "Color used for active borders, the header and priority badge.",
    ["Hotkey-Farbe"] = "Hotkey color",
    ["Textfarbe der beobachteten Tastenbelegung."] = "Text color of the observed key binding.",
    ["Cooldown-Farbe"] = "Cooldown color",
    ["Textfarbe für Timer, Aufladungen und Abdeckungszähler."] = "Text color for timers, charges and coverage counters.",
    ["Rollenfarben"] = "Role colors",
    ["Eigene Farben für jeden Heilungs-Kontext."] = "Individual colors for each healing context.",
    ["HUD-Optik zurücksetzen"] = "Reset HUD appearance",
    ["Setzt nur Schrift, Größen und Farben auf HeliHeal-Standard zurück."] = "Resets only fonts, sizes and colors to HeliHeal defaults.",
    ["OPTIK RESET"] = "RESET APPEARANCE",
    ["Profile & Reset"] = "Profiles & Reset",
    ["Separate Konfigurationen über AceDB verwalten oder sicher zurücksetzen."] = "Manage separate AceDB configurations or reset them safely.",
    ["AKTIVES PROFIL"] = "ACTIVE PROFILE",
    ["Profilname eingeben, um ein Profil anzulegen oder zu wechseln:"] = "Enter a profile name to create or switch profiles:",
    ["Profilname"] = "Profile name",
    ["PROFIL ÖFFNEN"] = "OPEN PROFILE",
    ["Cooldown-Simulation zurücksetzen"] = "Reset cooldown simulation",
    ["Entfernt nur die lokalen Laufzeittimer; deine Fähigkeiten bleiben erhalten."] = "Clears only local runtime timers; your abilities remain configured.",
    ["TIMER RESET"] = "RESET TIMERS",
    ["Alle Klassen-Hotkeys löschen"] = "Clear all class hotkeys",
    ["Entfernt nur deine hinterlegten Inputs; das feste 12.1-Prioritätspaket bleibt erhalten."] = "Clears configured inputs while retaining the static 12.1 priority pack.",
    ["HOTKEYS RESET"] = "RESET HOTKEYS",
    ["Komplettes Profil zurücksetzen"] = "Reset complete profile",
    ["Setzt Anzeige, Position und Prioritäten des aktiven Profils zurück."] = "Resets display, position and priorities for the active profile.",
    ["PROFIL RESET"] = "RESET PROFILE",
    ["Update-Verlauf"] = "Update History",
    ["Alle wichtigen Änderungen bleiben lokal und jederzeit einsehbar."] = "All important changes remain available locally at any time.",
    ["NEU IN HELIHEAL"] = "NEW IN HELIHEAL",
    ["UPDATE-VERLAUF"] = "UPDATE HISTORY",
    ["VERSTANDEN"] = "GOT IT",
    ["KONFIGURATION"] = "CONFIGURATION",
    ["ÜBERSICHT"] = "OVERVIEW",
    ["Anzeige & Verhalten"] = "Display & behavior",
    ["HUD-ELEMENTE"] = "HUD ELEMENTS",
    ["Icon, Hotkey & Cooldown"] = "Icon, hotkey & cooldown",
    ["PRIORITÄTEN"] = "PRIORITIES",
    ["Fähigkeiten & Inputs"] = "Abilities & inputs",
    ["PROFILE & RESET"] = "PROFILES & RESET",
    ["Konfiguration verwalten"] = "Manage configuration",
    ["Was ist neu?"] = "What's new?",
    ["SECURE INPUT TRACKER"] = "SECURE INPUT TRACKER",
    ["NO COMBAT DATA"] = "NO COMBAT DATA",
    ["/hh öffnet dieses Fenster  •  ESC schließt es"] = "/hh opens this window  •  ESC closes it",
    ["SCHLIESSEN"] = "CLOSE",
    ["Lokale Laufzeit: %ss • Ziel: %d"] = "Local duration: %ss • Goal: %d",
    ["Lokaler CD: %ss"] = "Local cooldown: %ss",
    ["Filler • kein lokaler CD"] = "Filler • no local cooldown",
    ["HOTKEY DOPPELT"] = "DUPLICATE HOTKEY",
    ["WIE HEALING RAIN"] = "SAME AS HEALING RAIN",
    ["HOTKEY HINTERLEGEN"] = "SET HOTKEY",
    ["DOPPELT"] = "DUPLICATE",
    ["What's New and Update History"] = "What's New and Update History",
    ["Einmaliges What's-New-Fenster beim ersten /hh nach einem Update."] = "One-time What's New window on the first /hh after an update.",
    ["Accountweiter Gesehen-Status statt wiederholter Hinweise pro Charakter oder Profil."] = "Account-wide seen state instead of repeated notices per character or profile.",
    ["Neue Update-History-Seite und direkter Zugriff über /hh changelog."] = "New Update History page with direct access through /hh changelog.",
    ["Automatische deutsche oder englische Oberfläche passend zur WoW-Clientsprache."] = "Automatic German or English interface based on the WoW client locale.",
    ["Warnungen für doppelt belegte unabhängige Hotkeys."] = "Warnings for duplicate independent hotkeys.",
    ["Versionierte Profilmigration und sicherer Out-of-Combat-Abgleich."] = "Versioned profile migration and safe out-of-combat reconciliation.",
    ["Diagnoseexport über /hh debug und automatisierte GitHub-Releases."] = "Diagnostic export through /hh debug and automated GitHub releases.",
    ["Nur Restoration Shaman und Restoration Druid aktivieren den Tracker."] = "Only Restoration Shaman and Restoration Druid activate the tracker.",
    ["Instant-GCD und veraltete Callback-Sperren korrigiert."] = "Fixed instant-GCD timing and stale callback locks.",
    ["Spec-, Talent- und Profilwechsel setzen lokale Zustände sicher zurück."] = "Spec, talent and profile changes safely reset local state.",
    ["Empfehlungen wechseln erst nach bestätigtem erfolgreichem Zauber."] = "Recommendations advance only after a confirmed successful spell.",
    ["Stormstream und Nature's-Swiftness-Aufladungen korrigiert."] = "Fixed Stormstream and Nature's Swiftness charge handling.",
    ["Instant-Cast-Erfolge vor Actionbar-Hooks werden kurz gepuffert."] = "Instant-cast successes before action-bar hooks are briefly cached.",
    ["Restoration-Druid-Prioritäten und lokale HoT-Zähler ergänzt."] = "Added Restoration Druid priorities and local HoT counters.",
    ["Optionale AoE-, Einzelziel- und Mana-Modi hinzugefügt."] = "Added optional AoE, Single Target and Mana modes.",
    ["Talentabhängige Shaman-Presets und Aufladungen verbessert."] = "Improved talent-aware Shaman presets and charges.",
    ["Statischer Hekili-inspirierter Healing-Priority-Tracker."] = "Static Hekili-inspired healing priority tracker.",
    ["Restoration-Shaman-Presets, Hotkey-Erfassung und lokale Timer."] = "Restoration Shaman presets, hotkey capture and local timers.",
    ["Modernes, bewegliches und anpassbares Icon-HUD."] = "Modern, movable and customizable icon HUD.",
    ["Selectable Interface Language"] = "Selectable Interface Language",
    ["Neue accountweite Sprachauswahl: Clientsprache, Deutsch oder English."] = "New account-wide language selection: Client Language, German or English.",
    ["Clientsprache bleibt der Standard und folgt automatisch der WoW-Einstellung."] = "Client Language remains the default and automatically follows the WoW setting.",
    ["Ein Sprachwechsel wird gespeichert und nach einem UI-Reload vollständig angewendet."] = "Language changes are saved and fully applied after a UI reload.",
    ["Wiederaufladezeit von Totem des Heilenden Flusses auf 17 Sekunden korrigiert."] = "Corrected Healing Stream Totem recharge time to 17 seconds.",
    ["Reliable Rapid Inputs"] = "Reliable Rapid Inputs",
    ["Hotkey-Entprellung arbeitet jetzt pro Taste statt global."] = "Hotkey debouncing now works per binding instead of globally.",
    ["Schnell aufeinanderfolgende unterschiedliche Fähigkeiten verlieren keine Cast-Bestätigung mehr."] = "Different abilities pressed in rapid succession no longer lose cast confirmation.",
    ["Riptide-Aufladungen bleiben dadurch mit erfolgreichen Instant-Casts synchron."] = "Riptide charges now remain synchronized with successful instant casts.",
    ["Lokale Holy-Power-Schätzung: %d/5"] = "Local Holy Power estimate: %d/5",
    ["Verwendung: /hh hp 0-5"] = "Usage: /hh hp 0-5",
    ["Gespeichertes Zaubertempo: %.1f%%"] = "Cached spell haste: %.1f%%",
    ["Rollen-Hinweis"] = "Role label",
    ["Zeigt AOE, SINGLE, BURST oder SAVE mittig auf passenden Heilfähigkeiten."] = "Shows AOE, SINGLE, BURST or SAVE in the center of matching healing abilities.",
    ["Holy Paladin Support"] = "Holy Paladin Support",
    ["Holy-Paladin-Prioritäten für Herald of the Sun und Lightsmith ergänzt."] = "Added Holy Paladin priorities for Herald of the Sun and Lightsmith.",
    ["Eigene Mythic+- und Raid-Pakete mit Standard-, AoE-, Einzelziel- und Mana-Modus hinzugefügt."] = "Added dedicated Mythic+ and Raid packs with Standard, AoE, Single Target and Mana modes.",
    ["Holy Power wird ausschließlich aus bestätigten eigenen Casts lokal geschätzt."] = "Holy Power is estimated locally from confirmed player casts only.",
    ["Divine Toll, Holy Prism, Holy Armaments und Holy-Shock-Aufladungen reagieren auf den Talent-Snapshot."] = "Divine Toll, Holy Prism, Holy Armaments and Holy Shock charges adapt to the talent snapshot.",
    ["Paladin Talent and Holy Power Model"] = "Paladin Talent and Holy Power Model",
    ["One Button Assistant and Live Holy Power"] = "One Button Assistant and Live Holy Power",
    ["Reliable Major Cooldown Confirmation"] = "Reliable Major Cooldown Confirmation",
    ["Compact Talent-Aware Priority List"] = "Compact Talent-Aware Priority List",
    ["Haste-Aware Paladin Recharge"] = "Haste-Aware Paladin Recharge",
    ["Context Labels for Filler Heals"] = "Context Labels for Filler Heals",
    ["Passende Heilfähigkeiten zeigen jetzt AOE, SINGLE, BURST oder SAVE mittig auf dem Icon."] = "Matching healing abilities now show AOE, SINGLE, BURST or SAVE in the center of the icon.",
    ["Holy Light wird als mana-effizientes SAVE und Flash of Light als schnelles BURST gekennzeichnet."] = "Holy Light is labeled as the mana-efficient SAVE option and Flash of Light as the fast BURST option.",
    ["Die Rollen-Hinweise sind standardmäßig aktiv und in den HUD-Optionen abschaltbar."] = "Role labels are enabled by default and can be disabled in the HUD options.",
    ["Die HUD-Optionen unterstützen jetzt Mausrad-Scrolling mit einem dezenten Scroll-Indikator."] = "HUD options now support mouse-wheel scrolling with a subtle scroll indicator.",
    ["Schriftart, Textkontur, Icon- und Textgrößen können jetzt live angepasst werden."] = "Font, outline, icon sizes and text sizes can now be adjusted live.",
    ["Akzent-, Hotkey-, Cooldown- und einzelne Rollenfarben sind vollständig konfigurierbar."] = "Accent, hotkey, cooldown and individual role colors are fully configurable.",
    ["Heiliger Schock verwendet jetzt die durch Zaubertempo reduzierte Wiederaufladezeit."] = "Holy Shock now uses its spell-haste-reduced recharge time.",
    ["Richturteil und Kreuzfahrerstoß verwenden dasselbe Tempo-Modell."] = "Judgment and Crusader Strike use the same haste model.",
    ["Zaubertempo wird nur außerhalb des Kampfes sicher gespeichert und im Kampf nicht als SecretValue verarbeitet."] = "Spell haste is cached safely only outside combat and is not processed as a SecretValue in combat.",
    ["Temporäre Tempo-Buffs im Kampf verändern die statische Schätzung absichtlich nicht."] = "Temporary in-combat haste buffs intentionally do not alter the static estimate.",
    ["Ausgeblendete Talent-Fähigkeiten hinterlassen keine leeren Zeilen mehr."] = "Hidden talent abilities no longer leave empty rows.",
    ["Sichtbare Fähigkeiten werden in den Optionen lückenlos neu nummeriert."] = "Visible abilities are renumbered without gaps in the options.",
    ["Interne Slots und gespeicherte Hotkeys bleiben dabei unverändert."] = "Internal slots and saved hotkeys remain unchanged.",
    ["Zornige Vergeltung wird nach einem erfolgreichen Spieler-Cast direkt bestätigt."] = "Avenging Wrath is confirmed directly after a successful player cast.",
    ["Shift-Belegungen, Makros und GCD-freie Cooldowns benötigen keinen vorher erkannten Actionbar-Hook mehr."] = "Shift bindings, macros and off-GCD cooldowns no longer require a previously observed action-bar hook.",
    ["Zorniger Kreuzritter und Aurenmeisterschaft verwenden denselben sicheren Bestätigungspfad."] = "Avenging Crusader and Aura Mastery use the same reliable confirmation path.",
    ["Doppelte Success-Events innerhalb des Cast-Fensters werden verworfen."] = "Duplicate success events inside the cast correlation window are discarded.",
    ["Der Blizzard One Button Assistant wird auf Standard-Aktionsleisten automatisch erkannt."] = "Blizzard's One Button Assistant is detected automatically on standard action bars.",
    ["Erfolgreiche OBA-Zauber aktualisieren passende HeliHeal-Cooldowns und Aufladungen."] = "Successful OBA spells update matching HeliHeal cooldowns and charges.",
    ["Die lesbare Holy Power des Spielers korrigiert die lokale Simulation nach jedem Cast."] = "The player's readable Holy Power corrects the local simulation after every cast.",
    ["Crusader Strike und Shield of the Righteous werden für OBA-Ressourcenänderungen berücksichtigt."] = "Crusader Strike and Shield of the Righteous are accounted for in OBA resource changes.",
    ["Walk Into Light erzeugt seit seiner 12.0.5-Überarbeitung keine Holy Power mehr."] = "Walk Into Light no longer generates Holy Power after its 12.0.5 redesign.",
    ["Divine Toll und Holy Prism verwenden mit Quickened Invocation jetzt korrekt 30 Sekunden Cooldown."] = "Divine Toll and Holy Prism now correctly use a 30-second cooldown with Quickened Invocation.",
    ["Paladin-Talentwahl steuert Divine Toll, Holy Prism, Holy Armaments, Wings, Crusader und Aura Mastery."] = "Paladin talent choices now control Divine Toll, Holy Prism, Holy Armaments, Wings, Crusader and Aura Mastery.",
    ["Holy Power wird als geordnete Folge bestätigter Casts berechnet und bei Refunds korrekt neu aufgebaut."] = "Holy Power is calculated as an ordered sequence of confirmed casts and replayed correctly after refunds.",
    ["Aurora, Walk Into Light, Ringing of the Heavens und rangabhängige Cooldown-Talente werden lokal simuliert."] = "Aurora, Walk Into Light, Ringing of the Heavens and rank-based cooldown talents are simulated locally.",
    ["Mit /hh hp 0-5 kann die lokale Schätzung bei einem nicht lesbaren Zufallsproc synchronisiert werden."] = "Use /hh hp 0-5 to synchronize the local estimate after an unreadable random proc.",
}

local deDE = {
    ["NEXT PRIORITY"] = "NÄCHSTE PRIORITÄT",
    ["What's New and Update History"] = "Neuigkeiten und Update-Verlauf",
    ["Beta Hardening"] = "Beta-Stabilisierung",
    ["Input Lifecycle"] = "Input-Lebenszyklus",
    ["Cast Confirmation"] = "Zauberbestätigung",
    ["Healing Modes and Druid Support"] = "Heilmodi und Druiden-Support",
    ["Initial Alpha"] = "Erste Alpha",
    ["Selectable Interface Language"] = "Auswählbare Oberflächensprache",
    ["Reliable Rapid Inputs"] = "Zuverlässige schnelle Eingaben",
    ["Holy Paladin Support"] = "Heiligpaladin-Unterstützung",
    ["Paladin Talent and Holy Power Model"] = "Paladin-Talente und Holy-Power-Modell",
    ["One Button Assistant and Live Holy Power"] = "Ein-Knopf-Assistent und echte Holy Power",
    ["Reliable Major Cooldown Confirmation"] = "Zuverlässige Bestätigung großer Cooldowns",
    ["Compact Talent-Aware Priority List"] = "Kompakte talentabhängige Prioritätsliste",
    ["Haste-Aware Paladin Recharge"] = "Tempoabhängige Paladin-Wiederaufladung",
    ["Context Labels for Filler Heals"] = "Kontext-Hinweise für direkte Heilungen",
}

local translations = enUS

function ns.SetLocale(mode)
    mode = mode == "deDE" and "deDE" or (mode == "enUS" and "enUS" or "auto")
    local requestedLocale = mode == "auto" and clientLocale or mode
    local effectiveLocale = requestedLocale == "deDE" and "deDE" or "enUS"
    translations = effectiveLocale == "deDE" and deDE or enUS
    ns.clientLocale = clientLocale
    ns.localeMode = mode
    ns.locale = effectiveLocale
    ns.localeFallback = mode == "auto"
        and clientLocale ~= "deDE" and clientLocale ~= "enUS" and clientLocale ~= "enGB"
    return effectiveLocale
end

function ns.Localize(key, ...)
    local value = translations[key] or (ns.locale == "deDE" and key) or enUS[key] or key
    if select("#", ...) > 0 then return value:format(...) end
    return value
end

ns.L = ns.Localize
ns.SetLocale("auto")
